### ISSUE TITLE
Database Error Code: Table 'civicrm.node' doesn't exist, 1146

### ISSUE THREAD

**Issue by mercurymotos** [sgladstone/com.pogstone.contenttokens#8]
The extension is throwing an error when saving contacts and also fails to present the usual array of tokens in the token selector.  Disable the extension, the problem goes away.  I un-installed and re-install the extension.

Using v3.1 on 4.7.24

NOTE: the CMS and CiviCRM tables are in different databases, accessed by the same user.

Error notice is:
Database Error Code: Table 'client_civicrm.node' doesn't exist, 1146
Additional Details:
Array
(
    [callback] => Array
        (
            [0] => CRM_Core_Error
            [1] => handle
        )

    [code] => -18
    [message] => DB Error: no such table
    [mode] => 16
    [debug_info] => SELECT type FROM .node n where status = 1 GROUP BY type [nativecode=1146 ** Table 'civicrm.node' doesn't exist]
    [type] => DB_Error
    [user_info] => SELECT type FROM .node n where status = 1 GROUP BY type [nativecode=1146 ** Table 'civicrm.node' doesn't exist]
    [to_string] => [db_error: message="DB Error: no such table" code=-18 mode=callback callback=CRM_Core_Error::handle prefix="" info="SELECT type FROM .node n where status = 1 GROUP BY type [nativecode=1146 ** Table 'client_civicrm.node' doesn't exist]"]
)

Backtrace is (with slight obscuration):

- #0 /home1/client/membership.client/sites/all/modules/civicrm/CRM/Core/Error.php(187): CRM_Core_Error::backtrace()
#1 [internal function](): CRM_Core_Error::handle(Object(DB_Error))
#2 /home1/client/membership.client/sites/all/modules/civicrm/packages/PEAR.php(921): call_user_func((Array:2), Object(DB_Error))
#3 /home1/client/membership.client/sites/all/modules/civicrm/packages/DB.php(985): PEAR_Error->__construct("DB Error: no such table", -18, 16, (Array:2), "SELECT type FROM .node n where status = 1 GROUP BY type [nativecode=1146 ** T...")
#4 /home1/client/membership.client/sites/all/modules/civicrm/packages/PEAR.php(575): DB_Error->__construct(-18, 16, (Array:2), "SELECT type FROM .node n where status = 1 GROUP BY type [nativecode=1146 ** T...")
#5 [internal function](): PEAR->_raiseError(Object(DB_mysqli), NULL, -18, NULL, NULL, "SELECT type FROM .node n where status = 1 GROUP BY type [nativecode=1146 ** T...", "DB_Error", TRUE)
#6 /home1/client/membership.client/sites/all/modules/civicrm/packages/PEAR.php(224): call_user_func_array((Array:2), (Array:8))
#7 /home1/client/membership.client/sites/all/modules/civicrm/packages/DB/common.php(1905): PEAR->__call("raiseError", (Array:7))
#8 /home1/client/membership.client/sites/all/modules/civicrm/packages/DB/common.php(1905): PEAR->raiseError(NULL, -18, NULL, NULL, "SELECT type FROM .node n where status = 1 GROUP BY type [nativecode=1146 ** T...", "DB_Error", TRUE)
#9 /home1/client/membership.client/sites/all/modules/civicrm/packages/DB/mysqli.php(933): DB_common->raiseError(-18, NULL, NULL, NULL, "1146 ** Table 'client_civicrm.node' doesn't exist")
#10 /home1/client/membership.client/sites/all/modules/civicrm/packages/DB/mysqli.php(403): DB_mysqli->mysqliRaiseError()
#11 /home1/client/membership.client/sites/all/modules/civicrm/packages/DB/common.php(1216): DB_mysqli->simpleQuery("SELECT type FROM .node n where status = 1 GROUP BY type")
#12 /home1/client/membership.client/sites/all/modules/civicrm/packages/DB/DataObject.php(2446): DB_common->query("SELECT type FROM .node n where status = 1 GROUP BY type")
#13 /home1/client/membership.client/sites/all/modules/civicrm/packages/DB/DataObject.php(1635): DB_DataObject->_query("SELECT type FROM .node n where status = 1 GROUP BY type")
#14 /home1/client/membership.client/sites/all/modules/civicrm/CRM/Core/DAO.php(362): DB_DataObject->query("SELECT type FROM .node n where status = 1 GROUP BY type")
#15 /home1/client/membership.client/sites/all/modules/civicrm/CRM/Core/DAO.php(1331): CRM_Core_DAO->query("SELECT type FROM .node n where status = 1 GROUP BY type", TRUE)
#16 /home1/client/membership.client/sites/default/files/civicrm/ext/com.pogstone.contenttokens/contenttokens.php(492): CRM_Core_DAO::executeQuery("SELECT type FROM .node n where status = 1 GROUP BY type", (Array:0))
#17 /home1/client/membership.client/sites/default/files/civicrm/ext/com.pogstone.contenttokens/contenttokens.php(9): contenttokens_getContentTypesInUse()
#18 /home1/client/membership.client/sites/all/modules/civicrm/CRM/Utils/Hook.php(270): contenttokens_civicrm_tokens((Array:1))
#19 /home1/client/membership.client/sites/all/modules/civicrm/CRM/Utils/Hook/DrupalBase.php(85): CRM_Utils_Hook->runHooks((Array:58), "civicrm_tokens", 1, (Array:1), NULL, NULL, NULL, NULL, NULL)
#20 /home1/client/membership.client/sites/all/modules/civicrm/Civi/Core/CiviEventDispatcher.php(86): CRM_Utils_Hook_DrupalBase->invokeViaUF(1, (Array:1), NULL, NULL, NULL, NULL, NULL, "civicrm_tokens")
#21 [internal function](): Civi\Core\CiviEventDispatcher::delegateToUF(Object(Civi\Core\Event\GenericHookEvent), "hook_civicrm_tokens", Object(Civi\Core\CiviEventDispatcher))
#22 /home1/client/membership.client/sites/all/modules/civicrm/vendor/symfony/event-dispatcher/Symfony/Component/EventDispatcher/EventDispatcher.php(164): call_user_func((Array:2), Object(Civi\Core\Event\GenericHookEvent), "hook_civicrm_tokens", Object(Civi\Core\CiviEventDispatcher))
#23 /home1/client/membership.client/sites/all/modules/civicrm/vendor/symfony/event-dispatcher/Symfony/Component/EventDispatcher/EventDispatcher.php(53): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch((Array:1), "hook_civicrm_tokens", Object(Civi\Core\Event\GenericHookEvent))
#24 /home1/client/membership.client/sites/all/modules/civicrm/vendor/symfony/event-dispatcher/Symfony/Component/EventDispatcher/ContainerAwareEventDispatcher.php(170): Symfony\Component\EventDispatcher\EventDispatcher->dispatch("hook_civicrm_tokens", Object(Civi\Core\Event\GenericHookEvent))
#25 /home1/client/membership.client/sites/all/modules/civicrm/Civi/Core/CiviEventDispatcher.php(47): Symfony\Component\EventDispatcher\ContainerAwareEventDispatcher->dispatch("hook_civicrm_tokens", Object(Civi\Core\Event\GenericHookEvent))
#26 /home1/client/membership.client/sites/all/modules/civicrm/CRM/Utils/Hook.php(164): Civi\Core\CiviEventDispatcher->dispatch("hook_civicrm_tokens", Object(Civi\Core\Event\GenericHookEvent))
#27 /home1/client/membership.client/sites/all/modules/civicrm/CRM/Utils/Hook.php(752): CRM_Utils_Hook->invoke((Array:1), (Array:1), NULL, NULL, NULL, NULL, NULL, "civicrm_tokens")
#28 /home1/client/membership.client/sites/all/modules/civicrm/CRM/Contact/BAO/Individual.php(208): CRM_Utils_Hook::tokens((Array:1))
#29 /home1/client/membership.client/sites/all/modules/civicrm/CRM/Contact/BAO/Contact.php(173): CRM_Contact_BAO_Individual::format((Array:45), Object(CRM_Contact_DAO_Contact))
#30 /home1/client/membership.client/sites/all/modules/civicrm/CRM/Contact/BAO/Contact.php(312): CRM_Contact_BAO_Contact::add((Array:45))
#31 /home1/client/membership.client/sites/all/modules/civicrm/CRM/Contact/Form/Contact.php(980): CRM_Contact_BAO_Contact::create((Array:45), TRUE, FALSE, TRUE)
#32 /home1/client/membership.client/sites/all/modules/civicrm/CRM/Core/Form.php(447): CRM_Contact_Form_Contact->postProcess()
#33 /home1/client/membership.client/sites/all/modules/civicrm/CRM/Core/QuickForm/Action/Upload.php(169): CRM_Core_Form->mainProcess()
#34 /home1/client/membership.client/sites/all/modules/civicrm/CRM/Core/QuickForm/Action/Upload.php(136): CRM_Core_QuickForm_Action_Upload->realPerform(Object(CRM_Contact_Form_Contact), "upload")
#35 /home1/client/membership.client/sites/all/modules/civicrm/packages/HTML/QuickForm/Controller.php(203): CRM_Core_QuickForm_Action_Upload->perform(Object(CRM_Contact_Form_Contact), "upload")
#36 /home1/client/membership.client/sites/all/modules/civicrm/packages/HTML/QuickForm/Page.php(103): HTML_QuickForm_Controller->handle(Object(CRM_Contact_Form_Contact), "upload")
#37 /home1/client/membership.client/sites/all/modules/civicrm/CRM/Core/Controller.php(351): HTML_QuickForm_Page->handle("upload")
#38 /home1/client/membership.client/sites/all/modules/civicrm/CRM/Utils/Wrapper.php(113): CRM_Core_Controller->run()
#39 /home1/client/membership.client/sites/all/modules/civicrm/CRM/Core/Invoke.php(284): CRM_Utils_Wrapper->run("CRM_Contact_Form_Contact", "New Contact", (Array:1))
#40 /home1/client/membership.client/sites/all/modules/civicrm/CRM/Core/Invoke.php(84): CRM_Core_Invoke::runItem((Array:13))
#41 /home1/client/membership.client/sites/all/modules/civicrm/CRM/Core/Invoke.php(52): CRM_Core_Invoke::_invoke((Array:3))
#42 /home1/client/membership.client/sites/all/modules/civicrm/drupal/civicrm.module(448): CRM_Core_Invoke::invoke((Array:3))
#43 [internal function](): civicrm_invoke("contact", "add")
#44 /home1/client/membership.client/includes/menu.inc(527): call_user_func_array("civicrm_invoke", (Array:2))
#45 /home1/client/membership.client/index.php(21): menu_execute_active_handler()
#46 {main}

**Comment by sgladstone** [comment]
What is the name of the database holding your Drupal tables? And what is the name of the database holding your CiviCRM tables?

**Comment by jayaprakash369** [comment]
@[sgladstone](https://github.com/sgladstone)same error here,
Initialization Error

Array
(
    [callback] => Array
        (
            [0] => CRM_Core_Error
            [1] => simpleHandler
        )
    [code] => -18
    [message] => DB Error: no such table
    [mode] => 16
    [debug_info] => SELECT id, name, value, domain_id, contact_id, is_domain, component_id, created_date, created_id
FROM civicrm_setting
WHERE (domain_id = 1) AND (is_domain = 1)
 [nativecode=1146 ** Table 'civicrm_cidd.civicrm_setting' doesn't exist]
    [type] => DB_Error
    [user_info] => SELECT id, name, value, domain_id, contact_id, is_domain, component_id, created_date, created_id
FROM civicrm_setting
WHERE (domain_id = 1) AND (is_domain = 1)
 [nativecode=1146 ** Table 'civicrm_cidd.civicrm_setting' doesn't exist]
    [to_string] => [db_error: message="DB Error: no such table" code=-18 mode=callback callback=CRM_Core_Error::simpleHandler prefix="" info="SELECT id, name, value, domain_id, contact_id, is_domain, component_id, created_date, created_id
FROM civicrm_setting
WHERE (domain_id = 1) AND (is_domain = 1)
 [nativecode=1146 ** Table 'civicrm_cidd.civicrm_setting' doesn't exist]"]
)

drupal version v9.3.5 
civicrm version v5.47.3
PHP 8.0.17
server centos 8
